### ISSUE TITLE
Error when adding parcel

### ISSUE THREAD

**Issue by jampez77** [jampez77/Evri#2]
This error originated from a custom integration.

Logger: custom_components.evri.coordinator
Source: helpers/update_coordinator.py:354
integration: Evri (documentation, issues)
First occurred: 21:31:39 (6 occurrences)
Last logged: 21:31:58

Unexpected error fetching evri data
Traceback (most recent call last):
  File "/config/custom_components/evri/coordinator.py", line 68, in _async_update_data
    uniqueIds=urllib.parse.quote(unique_ids[0], safe=":/?=&"),
                                 ~~~~~~~~~~^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/evri/coordinator.py", line 88, in _async_update_data
    raise UnknownError from err
custom_components.evri.coordinator.UnknownError

**Comment by 3ative** [comment]
Just installed here and is working. Nothing in the Logs for me.
